### ISSUE TITLE
facing problem, with compiler version reading 

### ISSUE THREAD

**Issue by abhiBlockchain** [rajeevgopalakrishna/Solstice#1]
I am using solc compiler version 0.5.1, even though err file containg.  Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.5.1;" 

also, it would be helpful if you will upload some screenshots of outputs of a tool to better understand about issues. as in my case, i am getting output just 
![screenshot from 2018-12-26 13-29-22](https://user-images.githubusercontent.com/35342679/50438034-4bf63a00-0912-11e9-8bc9-54bc5329b1db.png)
  is this a required output ? also in file ast file it is showing like this

 {
	"absolutePath" : "./contracts/QuillSTO.sol",
	"exportedSymbols" : {},
	"id" : 1,
	"nodeType" : "SourceUnit",
	"nodes" : [],
	"src" : "0:0:0"
}

**Comment by rajeevgopalakrishna** [comment]
Solstice has been tested with solc 0.4.24. solc version >= 0.5.0 has breaking changes, which includes changes to AST format. So I doubt it will work without non-trivial changes.

The output from Solstice is not reporting anything because I suspect the AST file doesn't have any information besides what you've shown.

**Comment by abhiBlockchain** [comment]
Can you show me some screenshots, for testing purpose so that, i will be get to know how exactly output will come and and also ast format from compiler 0.4.24

**Comment by rajeevgopalakrishna** [comment]
Run Solstice, with solc 0.4.24, on contracts in Tests/Analysers/Contracts/Real-World/ to see sample outputs.

**Comment by rajeevgopalakrishna** [comment]
Hope you were able to make progress. Please let me know if you run into other issues. Closing this issue. Thanks.
